### ISSUE TITLE
Crowding Distance Calculation different from paper

### ISSUE THREAD

**Issue by sp4ghet** [wreszelewski/nsga2#2]
I believe the crowding distance calculation is different from the one in the [NSGA-II(Deb, 2000) paper](http://repository.ias.ac.in/83498/).

The offending line of code is [here](https://github.com/wreszelewski/nsga2/blob/master/nsga2/utils.py#L58), and looks like:

```python:nsga2/utils.py
front[index].crowding_distance = (front[index+1].crowding_distance - front[index-1].crowding_distance) / (self.problem.max_objectives[m] - self.problem.min_objectives[m])
```

However, in (Deb 2000), the crowding distance is calculated as follows:

![image](https://cloud.githubusercontent.com/assets/8775460/21652627/6e733c56-d27b-11e6-9442-54b8424e796b.png)

The last line would correspond to the above code.
Is there a particular reasoning behind this? Thanks.

**Comment by kamilmielnik** [comment]
This implementation was not based on aforementioned paper.

I believe the denominator might be there just for normalization purposes, but this is a wild guess.

Please keep in mind that this was a university project and the code is no longer maintained.

**Comment by sp4ghet** [comment]
I see, thanks for the response. 
I totally understand, I'm going through and rewriting some of it for my own purposes but I might come back with more questions if I don't understand something. Thanks!

I tried replacing the crowding distance calculation with the one from the paper and the HVR didn't change by a significant amount so I'm sure both implementations are functional and the normalization might actually help where it's relevant.
